In [22]:
# from mido import MidiFile
import globalvar as GlobalVar
from funcMidi import * # create by SH
# MidiFileName = 'p20190612_midi_test_mix.mid'
# MidiFileName = 'p20190716_midi_test.mid'
# MidiFileName = 'p20190719 melody.mid'
# MidiFileName = 'p20190818 mix from TMD.mid'
# MidiFileName = 'Fleck, Bela - Daybreak.mid'
# MidiFileName = 'Aguado_12valses_Op1_No1.mid'
MidiFileName = 'Aguado_12valses_Op1_No1_downloadmidi.mid'

# midiArray = MidiCategorize(MidiFileName)
(midiArray, dicEvent) = MidiCategorize(MidiFileName)
dicNoteOnFingerBoard = funcCreatNoteDic()
midiArray

Track 0: 
capo = 0
tuning = [64, 59, 55, 50, 45, 40]
Notes in Finger board:
[64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76]
[59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71]
[55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67]
[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62]
[45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57]
[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52]


[[57, 0, 96, 'MIX', 0],
 [45, 0, 384, 'MIX', 0],
 [61, 96, 128, 'MIX', 0],
 [64, 128, 256, 'MIX', 0],
 [69, 256, 384, 'MIX', 0],
 [73, 384, 480, 'MIX', 1],
 [45, 384, 768, 'MIX', 1],
 [69, 480, 512, 'MIX', 1],
 [64, 512, 640, 'MIX', 1],
 [61, 640, 768, 'MIX', 1],
 [64, 768, 864, 'MIX', 2],
 [40, 768, 1152, 'MIX', 2],
 [62, 864, 896, 'MIX', 2],
 [59, 896, 1024, 'MIX', 2],
 [56, 1024, 1152, 'MIX', 2],
 [57, 1152, 1248, 'MIX', 3],
 [45, 1152, 1408, 'MIX', 3],
 [61, 1248, 1280, 'MIX', 3],
 [52, 1280, 1536, 'MIX', 3],
 [40, 1408, 1536, 'MIX', 3],
 [57, 1536, 1632, 'MIX', 4],
 [45, 1536, 1920, 'MIX', 4],
 [61, 1632, 1664, 'MIX', 4],
 [64, 1664, 1792, 'MIX', 4],
 [69, 1792, 1920, 'MIX', 4],
 [68, 1920, 2016, 'MIX', 5],
 [40, 1920, 2304, 'MIX', 5],
 [71, 2016, 2048, 'MIX', 5],
 [76, 2048, 2176, 'MIX', 5],
 [64, 2176, 2304, 'MIX', 5],
 [63, 2304, 2400, 'MIX', 6],
 [47, 2304, 2432, 'MIX', 6],
 [57, 2304, 2432, 'MIX', 6],
 [66, 2400, 2432, 'MIX', 6],
 [71, 2432, 2560, 'MEL', 7],
 [63, 2560, 2688,

In [23]:
# find Best Path 整理包
# 跑這隻之前 要把後面的func都跑過一次, debug系列除外
# calEventNum = 59

# 找到inf bug所在點--> calEventNum = 59, fromNumber = 216

# events, uniqTime = funcMidiEvents(midiArray, calEventNum = 59, fromNumber = 216)
events, uniqTime = funcMidiEvents(midiArray)
eventsNotes = funcArrangeEventNotes(events)
possible = funcNotes2Possibles(eventsNotes, dicNoteOnFingerBoard)
costBest = funcBestPath(eventsNotes, possible, printCostChord = False, printCostTran = False)
solutions, bestSolution = funcSolutions(costBest, possible, printOut = False)


In [26]:
print("len bestSolution =" + str(len(bestSolution[2])))
print("len eventsNotes =" + str(len(eventsNotes)))
print("len uniqTime =" + str(len(uniqTime)))
print("len events =" + str(len(events)))
bestSolution
eventsNotes
# events[0]
# print(events)
# print(eventsNotes)

len bestSolution =264
len eventsNotes =264
len uniqTime =271
len events =124


[[57, 45],
 [-45, 61],
 [-45, 64],
 [-45, 69],
 [73, 45],
 [-45, 69],
 [-45, 64],
 [-45, 61],
 [64, 40],
 [-40, 62],
 [-40, 59],
 [-40, 56],
 [57, 45],
 [-45, 61],
 [-45, 52],
 [-52, 40],
 [57, 45],
 [-45, 61],
 [-45, 64],
 [-45, 69],
 [68, 40],
 [-40, 71],
 [-40, 76],
 [-40, 64],
 [63, 47, 57],
 [-47, -57, 66],
 [71],
 [63, 57],
 [64, 52, 56],
 [57, 45],
 [-45, 61],
 [-45, 64],
 [-45, 69],
 [73, 45],
 [-45, 69],
 [-45, 64],
 [-45, 61],
 [64, 40],
 [-40, 62],
 [-40, 59],
 [-40, 56],
 [57, 45],
 [-45, 61],
 [-45, 52],
 [-52, 40],
 [57, 45],
 [-45, 61],
 [-45, 64],
 [-45, 69],
 [68, 40],
 [-40, 71],
 [-40, 76],
 [-40, 64],
 [63, 47, 57],
 [-47, -57, 66],
 [71],
 [63, 57],
 [64, 52, 56],
 [56, 50],
 [-50, 59],
 [-50, 64],
 [-50, 64],
 [56, 49],
 [-49, 59],
 [-49, 64],
 [-49, 64],
 [59, 52],
 [-52, 62],
 [-52, 68],
 [-52, 68],
 [69, 45],
 [-45, 64],
 [-45, 61],
 [-45, 57],
 [61, 54],
 [-54, 64],
 [-54, 70],
 [-54, 70],
 [71, 50],
 [-50, 66],
 [-50, 62],
 [59, 47],
 [57, 52],
 [-52, 61],
 [

In [17]:
npUniqTime = np.array(uniqTime)# - uniqTime[:-1]

diffUniqTime = npUniqTime[1:] - npUniqTime[:-1]
timeResolution = np.min(diffUniqTime)
print("timeResolution =" + str(timeResolution))
(val, counts) = np.unique(diffUniqTime, return_counts = True)
quaver = val[np.argmax(counts)] # assume that most common time interval is the quaver (8th note)
print("quaver =" + str(quaver))

diffUniqTime
# minDiffUniqTime = min(diffUniqTime)
# minDiffUniqTime

timeResolution =240
quaver =480


array([240, 240, 960, 480, 480, 480, 480, 480, 960, 960])

In [18]:

printEvents = copy.deepcopy(events)
time = 0
# max(npUniqTime)
for time in range(0, max(npUniqTime)+1, timeResolution):
    for event in events:
#         print(event[0][3])
        if event[0][3] == "MEL":
            events.remove(event)
            print(event)
#         if time 
#     if 
# #     event = printEvents.pop(0)
#     print(event)
    

[[45, 0, 240, 'MEL']]
[[57, 480, 1440, 'MEL']]
[[53, 240, 480, 'MEL']]


In [51]:
nonZeroTest = np.append(npUniqTime,[111])
nonZeroTest
# npUniqTime
# 檢查time resolution有沒有選正確
if np.shape(np.nonzero(npUniqTime % timeResolution))[1] != 0:
    print("Time Resolution is wrong, there might be a odd beat in time sequnence")


In [16]:
np.histogram(diffUniqTime)

(array([2, 0, 0, 5, 0, 0, 0, 0, 0, 3]),
 array([240., 312., 384., 456., 528., 600., 672., 744., 816., 888., 960.]))

In [31]:
events
uniqTime

[0, 240, 480, 1440, 1920, 2400, 2880, 3360, 3840, 4800, 5760]

In [20]:
bestSolution[2]

[[[5, 0, 0]],
 [[4, 3, 3]],
 [[3, 2, 2]],
 [[3, 2, 2], [6, 0, 0]],
 [[6, 0, 0], [2, 3, 3]],
 [[6, 0, 0], [2, 1, 1]],
 [[6, 0, 0], [3, 0, 0]],
 [[5, 3, 3], [4, 2, 2], [2, 1, 1], [3, 0, 0], [1, 0, 0]],
 [[4, 0, 0], [3, 2, 1], [2, 3, 3], [1, 2, 2]]]